# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

#### Create an array of 5 zeros 

#### Create an array of 5 ones

#### Create an array of 5 tens

#### Create an array of the integers from 0 to 30

#### Create an array of all the even integers from 0 to 30

#### Create a 3x3 identity matrix

#### Use NumPy to generate a random number between 0 and 1

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [43]:
mat = np.arange(1,36).reshape(5,7)
mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [39]:
# Write your code here to match the output shown in the cell below.
# Do NOT run the cell below, or you'll lose access to the expected output.



array([[22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [30]:
# Write your code here to match the output shown in the cell below.
# Do NOT run the cell below, or you'll lose access to the expected output.



array([[16, 17, 18, 19, 20, 21],
       [23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35]])

In [31]:
# Write your code here to match the output shown in the cell below.
# Do NOT run the cell below, or you'll lose access to the expected output.



array([[14],
       [21],
       [28],
       [35]])

### Perform the following tasks:

#### Calculate the total sum of all elements in mat.

#### Compute the standard deviation of the values in mat.

#### Find the sum of the elements in each column of mat.